### ISSUE TITLE
'puro ls' defaults to --no-color in git bash

### ISSUE THREAD

**Issue by tksoh** [pingbird/puro#53] opened 2023-09-27 08:22 UTC
Something strange with puro running in Git Bash on Windows 11. In VSCode terminal, `puro ls` always show its output in colors. But in git bash, it does not show the colors by default, and I have to add the `--color` option to force it to show the colors. What am I missing?

Screenshot of git bash for references.

![Screenshot 2023-09-27 161356](https://github.com/pingbird/puro/assets/494222/d56221aa-8533-46e0-8a53-397fcc0ba3f7)

**Comment by pingbird** [comment] 2023-09-27 16:35
It uses [Stdout.supportsAnsiEscapes](https://api.flutter.dev/flutter/dart-io/Stdin/supportsAnsiEscapes.html) to detect whether or not the current shell supports colors, but not all shells are supported.

I was able to reproduce it locally and it looks like a known issue in Dart: https://github.com/dart-lang/sdk/issues/31606

**Comment by pingbird** [comment] 2023-09-27 16:45
This should be fixed in the next release

**Closed by pingbird** 2023-09-27 16:45 UTC
