### ISSUE TITLE
"The Flutter SDK is not available." when running build_runner

### ISSUE THREAD

**Issue by fennelhans** [pingbird/puro#12] opened 2023-05-17 15:12 UTC
I'm not able to run my build_runner commands when using Puro. Am I doing something wrong, or is this a legit bug (and reason I shouldn't use puro for now)?

![image](https://github.com/PixelToast/puro/assets/98828887/58c1ff25-2594-45ef-930a-8315462cb84c)

```
[i] Puro 1.2.6 (distribution/darwin-x64)
    Dart 2.19.5 (stable) (Mon Mar 20 17:09:37 2023 +0000) on "macos_x64"
```

**Comment by fennelhans** [comment] 2023-05-17 15:14
Also, does it have anything to do with this?

```
$ puro gc
[x] PathNotFoundException: Cannot retrieve access time, path = '/Users/hans/.puro/shared/caches/4c8c31f591882b3c668992d2e9da761118899f38/engine-dart-sdk.stamp' (OS Error: No such file or directory, errno = 2)
    #0      _File.throwIfError (dart:io/file_impl.dart:629)
    #1      _File.lastAccessedSync (dart:io/file_impl.dart:397)
    #2      ForwardingFile.lastAccessedSync (package:file/src/forwarding/forwarding_file.dart:44)
    #3      collectGarbage (package:puro/src/env/gc.dart:35)
    #4      GcCommand.run (package:puro/src/commands/gc.dart:15)
    #5      CommandRunner.runCommand (package:args/command_runner.dart:212)
    #6      PuroCommandRunner.runCommand (package:puro/src/command.dart:342)
    #7      CommandRunner.run.<anonymous closure> (package:args/command_runner.dart:122)
    #8      new Future.sync (dart:async/future.dart:302)
    #9      CommandRunner.run (package:args/command_runner.dart:122)
    #10     main (package:puro/src/cli.dart:232)
    #11     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295)
    #12     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:192)

[x] Puro crashed! Please file an issue at https://github.com/PixelToast/puro
    Consider running the command with a higher log level: `--log-level=4`
```

**Comment by PixelToast** [comment] 2023-05-17 19:51
I could probably improve the error message here, what did you do to fix it?

**Comment by fennelhans** [comment] 2023-05-17 20:05
> I could probably improve the error message here, what did you do to fix it?

I'm actually questioning whether I _did_ at this point. I was bouncing between puro and git versions of Flutter. I was able to replicate the issue with the git version of flutter if I ran `dart run` instead of `flutter pub run`, so I thought that might be the issue. Now, I'm not so sure.

**Comment by ngee147** [comment] 2023-05-19 07:10
I having other issue on command ```build_runner build``` also.

<img width="993" alt="Screenshot 2023-05-19 at 3 00 25 PM" src="https://github.com/PixelToast/puro/assets/15373825/fe6c9558-19f9-42f2-9fad-0cc050a3ab02">

```
[i] Puro 1.2.6 (distribution/darwin-x64)
    Dart 2.19.5 (stable) (Mon Mar 20 17:09:37 2023 +0000) on "macos_x64"
    ```
    
    ```
     env    (stable / 3.10.1 / d3d8effc68)
```

**Comment by npatriquin** [comment] 2023-05-24 07:05
Had a similar problem today which included this message along with DARTSDK issue I could not resolve. Had to go back to pre-puro implementation

**Because depends on lints >=2.0.0 which requires SDK version >=2.17.0-206.0.dev <3.0.0 or ^3.0.0-417, version solving failed**

**Comment by PixelToast** [comment] 2023-05-24 16:24
@npatriquin That sounds like a mismatch between the version of something that depends on lints and the Dart SDK you have selected, the full error message would help diagnose it more but it doesn't seem like an issue with Puro.

**Comment by npatriquin** [comment] 2023-05-24 18:07
> @npatriquin That sounds like a mismatch between the version of something that depends on lints and the Dart SDK you have selected, the full error message would help diagnose it more but it doesn't seem like an issue with Puro.

I agree, it is a mismatch in DART SDK lib but it worked fine before installing Puro and no matter  what flutter version I selected with Puro 2.8, 2.10, 3.0... it remained a problem.  It seems Puro or a flutter install of 3.10 changed something that was not getting set back when I tried to back to flutter 2.10.

I understand this may not be a Puro problem and, now that I'm working again, I don't want to mess up my working flutter environment again to try and figure it out. I was trying to install Puro to avoid these types of problems.

Otherwise, Puro was working great and I think it's a great tool.

No need to try and resolve this for me.

Thanks,
Norm

**Comment by getBoolean** [comment] 2023-06-16 05:01
Running into this again today on Windows with a flutter package in my app mono repo, but only with one package. All the other build_runner packages are working

working: `packages\features\feature_first`
not working: `packages\utils\env`

I'm kinda stumped on what to do. I've tried `flutter pub cache clean`, `flutter clean`, and reinstalling puro but i havent been able to fix it

I have a mac setup with fvm and it was working. Switched over to my windows machine to test stuff, pulled down the latest code, and i ran into this

**Comment by getBoolean** [comment] 2023-06-16 06:06
I may have figured out why it is happening for me. Any time I add a package by path, `dart run` stops working

looks like its any package that has a dependency with a path like this:

```yaml
dependencies:
  ...
  constants:
    path: ../constants
```

`dart run` output with path dependency: 

```bash
The Flutter SDK is not available.
```

`dart run` output without path dependency: (just showing that the dart command works)

```bash
Could not find `bin\app_name.dart` in package `app_name`.
```

**Comment by getBoolean** [comment] 2023-06-16 06:07
@fennelhans did your app depend on another package by path?

**Comment by pingbird** [comment] 2023-06-16 19:53
I figured out that the dart tool needs a `FLUTTER_ROOT` environment variable in order to detect the Flutter SDK. This should be fixed in the next version.

Thanks @getBoolean for helping with reproducing the issue!

**Closed by pingbird** 2023-06-16 19:53 UTC

**Comment by hanskokx** [comment] 2023-06-16 22:06
Oh, yeah, it did. I had created a UI package, one level up in the monorepo. I bet that's it. Unfortunately, I'm no longer with the company and don't have any sort of access to the codebase to test anything, but if it's a path issue, it's trivial to replicate.
