### ISSUE TITLE
version file cannot be found

### ISSUE THREAD

**Issue by gaetschwartz** [pingbird/puro#20] opened 2023-07-24 07:05 UTC
After creating a new environment, there seems to be an issue where puro doesn't create a `version` file in the flutter installation folder. This causes `flutter doctor` and other commands to fail.

![Screenshot 2023-07-24 at 09 03 37](https://github.com/pingbird/puro/assets/25441359/92b8b366-b976-4ffb-a679-3596a497610b)

**Comment by pingbird** [comment] 2023-07-24 15:38
The last time this happened it was due to someone hitting ctrl-c in the middle of `puro create`.

Are you able to reproduce this with a fresh environment? If so, post the verbose logs (`--log-level=4`) of both the `puro create beta` and `puro -e beta --log-level=4 flutter doctor` commands. You can delete the current environment with `puro rm beta`.

**Comment by gaetschwartz** [comment] 2023-07-24 16:24
I did try a few times and every time I get the same result. Note that doing `puro flutter doctor` works and seems to create the said file, fixing my issue afterwards.

**Comment by pingbird** [comment] 2023-07-25 16:30
I am unable to reproduce and can't do much else without the logs mentioned before

**Comment by gaetschwartz** [comment] 2023-07-28 16:49
I will try to give you a repro when I'm back from holidays :)

**Comment by gaetschwartz** [comment] 2023-08-06 08:36
After some investigation, here is how to trigger my issue:

```bash
$ puro rm beta
$ puro create beta
$ puro use beta
$ puro flutter pub add collection # or any other command
```
![Screenshot 2023-08-06 at 10 35 40](https://github.com/pingbird/puro/assets/25441359/deeecf08-56ee-4349-b02b-c5e0ebe45125)

**Comment by pingbird** [comment] 2023-08-11 21:47
Ah, I managed to reproduce it, thanks!

I'll have time to work on it some time next week, sorry for the delay

**Comment by gaetschwartz** [comment] 2023-08-20 09:11
Hi have you managed to find a fix or at least a workaround ? I still can't use puro properly because of this :/

**Comment by pingbird** [comment] 2023-08-22 18:34
Finally figured out why this is happening, a little while ago Flutter started using `flutter/bin/cache/flutter.version.json` instead of `flutter/version`: https://github.com/flutter/flutter/commit/3246808cd26e3a35aeb2dfa5081af20b7683a5b4 new installations will detect `flutter.version.json` in the shared engine cache and not generate the legacy `version` which tools like pub still use.

This is quite a mess for me to fix because puro assumes `flutter/bin/cache` only contains engine-specific data, I will either have to patch the flutter tool to use a different version file or do symlink surgery on the cache directory.

As a quick mitigation I will try deleting `flutter.version.json` before every invocation, it won't fix the broken version detection but should allow pub commands to function normally.

**Closed** 2023-08-24 14:18 UTC
