### ISSUE TITLE
Puro crashing upon setting an environment on Ubuntu 

### ISSUE THREAD

**Issue by i-am-ijaz** [pingbird/puro#68] opened 2024-01-14 13:43 UTC
error: 2968 bytes of body are still expected
    fetch-pack: unexpected disconnect while reading sideband packet
    fatal: early EOF
    fatal: fetch-pack: invalid index-pack output
[=====          ] Downloading engine
[x] Bad state: git subprocess failed with exit code 128
    #0      GitClient._ensureSuccess (package:puro/src/git.dart:109)
    #1      GitClient.clone (package:puro/src/git.dart:167)
    <asynchronous suspension>
    #2      GitClient.cloneWithProgress.<anonymous closure> (package:puro/src/git.dart:181)
    <asynchronous suspension>
    #3      ProgressNode.wrap (package:puro/src/progress.dart:68)
    <asynchronous suspension>
    #4      GitClient.cloneWithProgress (package:puro/src/git.dart:179)
    <asynchronous suspension>
    #5      fetchOrCloneShared (package:puro/src/env/create.dart:205)
    <asynchronous suspension>
    #6      cloneFlutterWithSharedRefs (package:puro/src/env/create.dart:332)
    <asynchronous suspension>
    #7      createEnvironment.<anonymous closure> (package:puro/src/env/create.dart:148)
    <asynchronous suspension>
    #8      lockFile (package:puro/src/file_lock.dart:68)
    <asynchronous suspension>
    #9      createEnvironment (package:puro/src/env/create.dart:109)
    <asynchronous suspension>
    #10     CommandRunner.runCommand (package:args/command_runner.dart:212)
    <asynchronous suspension>
    #11     main (package:puro/src/cli.dart:256)
    <asynchronous suspension>
    
[x] Puro crashed! Please file an issue at https://github.com/pingbird/puro
    Consider running the command with a higher log level: `--log-level=4`

**Comment by pingbird** [comment] 2024-01-14 22:25
Looks like a duplicate of https://github.com/pingbird/puro/issues/67

I am unable to reproduce this error unfortunately

**Closed by pingbird** 2024-01-14 22:25 UTC
